language: python
python:
- 2.7
install:
- pip install -r requirements.txt
- pip install .
- pip install -e git+https://github.com/napalm-automation/napalm-base.git@develop#egg=napalm-base
deploy:
  provider: pypi
  user: dbarroso
  password:
    secure: IIifRr9K771snku+qI7yz8T/cJC4ZO/fUYUNILhMB5eQtF2/MAEU7W1owGfcIqE9SW7fhPAXqVrnb7AcdFyjjbkZn6uoYYlh5LrQaCXgbfol5Yg+OSsRKFwhEOBcKFrtqz3W6UPunN6CX4v2gn2UCmWSyQ3XERgqKxobBVSOMb1G9PTy/Zk0ZUvGJc05bxWj3xuVQKg904VpnhQJ6q1h4d9SV+dQClP4eDRbEwe+ICKX3S2JPa/PiJfWrIsCL12yT+iZ/aiDwfSBjh+o3HMdt98cB3FkHAibEZnvpLOpUCmjX1rMyqyJEqVgDM1mQ4vyoYO5DNFv94ZufGJnJP+TIbkkSaFy9ZpeC2V+7K03TM+g1rZD3BKK50u3kL86KsHao14SZHV58l7/b3023IUr4MwrQgoLlHMhw9IFFC8bYmP/6aylae5fR/+5inGloSByzWLAKKQ0FLPPkCoeukmldyphjZ8HnGdhEu566kO9R5gxJ4edsbeimsRAO3oZ/EByQcgOytJjVKjMpn7fhiSblJO8KB4+M5d5fXUn5RZ31P3g8RFfG1Jqx2l9eOd4i8u9l3NkRd9WO8q5wyF/hvC/u4RcIMnRYl5hPWMBNY6uGGj7aq7o+XETTLVFirCwHBKre6OLdaVpW1ZciJP07Xb9qhyPLCeP3E9VM/OAz9rs5KI=
  on:
    tags: true
    branch: master
script:
- cd test/unit
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_arp_table
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_bgp_config
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_bgp_neighbors
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_environment
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_facts
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_interfaces
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_interfaces_counters
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_interfaces_ip
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_lldp_neighbors
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_lldp_neighbors_detail
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_mac_address_table
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_ntp_peers
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_ntp_stats
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_route_to
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_snmp_information
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_users
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_traceroute
- nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_bgp_neighbors_detail
- cd ../..
