language: python

python:
    - 2.7

install:
  - pip install -r requirements.txt
  - pip install .

script:
  - cd test/unit
  # testing junos getters
  - nosetests -v TestJunOSDriver:TestGetterJunOSDriver.test_get_bgp_config
  - nosetests -v TestJunOSDriver:TestGetterJunOSDriver.test_get_bgp_neighbors
  - nosetests -v TestJunOSDriver:TestGetterJunOSDriver.test_bgp_neighbors_detail
  - nosetests -v TestJunOSDriver:TestGetterJunOSDriver.test_get_environment
  - nosetests -v TestJunOSDriver:TestGetterJunOSDriver.test_get_facts
  - nosetests -v TestJunOSDriver:TestGetterJunOSDriver.test_get_interfaces
  - nosetests -v TestJunOSDriver:TestGetterJunOSDriver.test_get_interfaces_counters
  - nosetests -v TestJunOSDriver:TestGetterJunOSDriver.test_get_lldp_neighbors
  - nosetests -v TestJunOSDriver:TestGetterJunOSDriver.test_get_lldp_neighbors_detail
  - nosetests -v TestJunOSDriver:TestGetterJunOSDriver.test_get_arp_table
  - nosetests -v TestJunOSDriver:TestGetterJunOSDriver.test_get_ntp_peers
  - nosetests -v TestJunOSDriver:TestGetterJunOSDriver.test_get_interfaces_ip
  - nosetests -v TestJunOSDriver:TestGetterJunOSDriver.test_get_mac_address_table
  # testing eos getters
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_bgp_config
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_bgp_neighbors
  # not implemented on eos
  # - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_bgp_neighbors_detail
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_environment
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_facts
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_interfaces
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_interfaces_counters
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_lldp_neighbors
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_lldp_neighbors_detail
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_arp_table
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_ntp_peers
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_interfaces_ip
  - nosetests -v TestEOSDriver:TestGetterEOSDriver.test_get_mac_address_table
  # testing iosxr getters
  - nosetests -v TestIOSXRDriver:TestGetterIOSXRDriver.test_get_bgp_config
  - nosetests -v TestIOSXRDriver:TestGetterIOSXRDriver.test_get_bgp_neighbors
  - nosetests -v TestIOSXRDriver:TestGetterIOSXRDriver.test_bgp_neighbors_detail
  - nosetests -v TestIOSXRDriver:TestGetterIOSXRDriver.test_get_environment
  - nosetests -v TestIOSXRDriver:TestGetterIOSXRDriver.test_get_facts
  - nosetests -v TestIOSXRDriver:TestGetterIOSXRDriver.test_get_interfaces
  - nosetests -v TestIOSXRDriver:TestGetterIOSXRDriver.test_get_interfaces_counters
  - nosetests -v TestIOSXRDriver:TestGetterIOSXRDriver.test_get_lldp_neighbors
  - nosetests -v TestIOSXRDriver:TestGetterIOSXRDriver.test_get_lldp_neighbors_detail
  - nosetests -v TestIOSXRDriver:TestGetterIOSXRDriver.test_get_arp_table
  - nosetests -v TestIOSXRDriver:TestGetterIOSXRDriver.test_get_ntp_peers
  - nosetests -v TestIOSXRDriver:TestGetterIOSXRDriver.test_get_interfaces_ip
  - nosetests -v TestIOSXRDriver:TestGetterIOSXRDriver.test_get_mac_address_table
# testing nxos getters
  - nosetests -v TestNXOSDriver:TestGetterNXOSDriver.test_get_facts
  - nosetests -v TestNXOSDriver:TestGetterNXOSDriver.test_get_interfaces
  - nosetests -v TestNXOSDriver:TestGetterNXOSDriver.test_get_lldp_neighbors
  - nosetests -v TestNXOSDriver:TestGetterNXOSDriver.test_get_lldp_neighbors_detail
  - nosetests -v TestNXOSDriver:TestGetterNXOSDriver.test_get_arp_table
  - nosetests -v TestNXOSDriver:TestGetterNXOSDriver.test_get_ntp_peers
  - nosetests -v TestNXOSDriver:TestGetterNXOSDriver.test_get_interfaces_ip
  - nosetests -v TestNXOSDriver:TestGetterNXOSDriver.test_get_mac_address_table
# testing pluribus getters
  - nosetests -v TestPluribusDriver:TestGetterPluribusDriver.test_get_facts
  - nosetests -v TestPluribusDriver:TestGetterPluribusDriver.test_get_interfaces
  - nosetests -v TestPluribusDriver:TestGetterPluribusDriver.test_get_lldp_neighbors
  - nosetests -v TestPluribusDriver:TestGetterPluribusDriver.test_get_lldp_neighbors_detail
  - nosetests -v TestPluribusDriver:TestGetterPluribusDriver.test_get_ntp_peers
  - nosetests -v TestPluribusDriver:TestGetterPluribusDriver.test_get_mac_address_table
# testing ios getters
  - nosetests -v TestIOSDriver:TestGetterIOSDriver.test_get_bgp_neighbors
  - nosetests -v TestIOSDriver:TestGetterIOSDriver.test_get_environment
  - nosetests -v TestIOSDriver:TestGetterIOSDriver.test_get_facts
  - nosetests -v TestIOSDriver:TestGetterIOSDriver.test_get_interfaces
  - nosetests -v TestIOSDriver:TestGetterIOSDriver.test_get_interfaces_counters
  - nosetests -v TestIOSDriver:TestGetterIOSDriver.test_get_interfaces_ip
  - nosetests -v TestIOSDriver:TestGetterIOSDriver.test_get_lldp_neighbors
  - nosetests -v TestIOSDriver:TestGetterIOSDriver.test_ios_only_bgp_time_conversion #IOS only test
